// <auto-generated />
using System;
using LoanManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230821181518_AddTablesToDB")]
    partial class AddTablesToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanManagementSystem.Models.CustomerLoanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanRequiredAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanSactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loanStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerLoanHistories");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.DocumentMaster", b =>
                {
                    b.Property<string>("DocumentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentCode");

                    b.ToTable("DocumentMasters");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanApplication", b =>
                {
                    b.Property<int>("ApplicationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationNumber"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustemerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanEMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanTenureInMonth")
                        .HasColumnType("int");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("RequiredLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ApplicationNumber");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanDocumentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentMappings");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanType", b =>
                {
                    b.Property<string>("LoanCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanInterestRatePerAnnum")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("MaximumAgeRequired")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinimumAgeRequired")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoanCode");

                    b.ToTable("LoanTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
